## Numpy

In [1]:
import numpy as np

## The Basics:-

In [5]:
arr1=np.array([1,2,3,4])
print(arr1)

[1 2 3 4]


In [13]:
arr2=np.array([[10.0,11.0,12.0],[11.5,12.5,13.5]])
print(arr2)

[[10.  11.  12. ]
 [11.5 12.5 13.5]]


In [14]:
#Getting the dimesnsions of an array
print(arr1.ndim)
print(arr2.ndim) 

1
2


In [17]:
#Getting the shape of an array
print(arr1.shape,type(arr1.shape))
print(arr2.shape,type(arr2.shape))

(4,) <class 'tuple'>
(2, 3) <class 'tuple'>


In [20]:
#Get datatype of array elements
print(arr1.dtype)
print(arr2.dtype)

int32
float64


In [22]:
#Specifying the datatype when creating arrays
arr3=np.array([1,2,3,4],'int16')
print(arr3,arr3.dtype)

[1 2 3 4] int16


In [24]:
#Getting the number of bytes of each item in an array
print(arr1.itemsize)
print(arr2.itemsize)
print(arr3.itemsize)

4
8
2


In [29]:
#get total no. of bytes in an array
print(arr1.itemsize*arr1.size) #arr.size is for the no. of items in an array
print(arr1.nbytes)
print(arr2.itemsize*arr2.size) 
print(arr2.nbytes)
print(arr3.itemsize*arr3.size) 
print(arr3.nbytes)

16
16
48
48
8
8


## Accessing/Changing specific elements,rows,columns,etc. :-

In [15]:
a1=np.array([[1,2,3,4,5,6,7],[8,9,10,11,12,13,14]])
print(a1)

[[ 1  2  3  4  5  6  7]
 [ 8  9 10 11 12 13 14]]


In [5]:
a1.shape

(2, 7)

In [10]:
#accessing elements [r] [c]:-
print(a1[1][5])
print(a1[1,5])
print(a1[-1,-2]) # negative indexing works here as well

13
13
13


In [13]:
#accessing an entire row:-
print(a1[0])
print(a1[0,:])

[1 2 3 4 5 6 7]
[1 2 3 4 5 6 7]


In [16]:
#getting a specific column:-
print(a1[:,0])
print(a1[:,6])

[1 8]
[ 7 14]


In [23]:
#Getting a little more fancy [startindex:endindex:stepsize]
print(a1[1,0:8:2])
print(a1[1,::2])
print(a1[1,::-1])

[ 8 10 12 14]
[ 8 10 12 14]
[14 13 12 11 10  9  8]


In [24]:
a1[1,5]=20
print(a1)

[[ 1  2  3  4  5  6  7]
 [ 8  9 10 11 12 20 14]]


In [25]:
a1[1,5]=13
print(a1)

[[ 1  2  3  4  5  6  7]
 [ 8  9 10 11 12 13 14]]


In [29]:
# Changing the values of an entire column:-
a1[:,2]=15 # with just one value
print(a1)
a1[:,2]=[-1,-2] # with multiple values in the same shape(same shape is necessary)
print(a1)

[[ 1  2 15  4  5  6  7]
 [ 8  9 15 11 12 13 14]]
[[ 1  2 -1  4  5  6  7]
 [ 8  9 -2 11 12 13 14]]


#### 3D Array Example

In [33]:
arr1=np.array([[[1,2],[2,3]],[[3,4],[5,6]],[[7,8],[8,9]]])
print(arr1)
print(arr1.shape)

[[[1 2]
  [2 3]]

 [[3 4]
  [5 6]]

 [[7 8]
  [8 9]]]
(3, 2, 2)


In [36]:
#accessing an element here:- (Work outside in)
print(arr1[1,1,0])
print(arr1[:,1,:])

5
[[2 3]
 [5 6]
 [8 9]]


In [39]:
#replacing in a 3D array
arr1[:,1,:]=np.array([[-2,-3],[-5,-6],[-8,-9]]) #dimensions should be same
print(arr1)

[[[ 1  2]
  [-2 -3]]

 [[ 3  4]
  [-5 -6]]

 [[ 7  8]
  [-8 -9]]]


## Initializing Different Types of Arrays:-

In [48]:
# All zeros matrix
arr=np.zeros((3,2,3))
print(arr)
print()
arr=np.zeros((3,2,3),"int32")
print(arr)

[[[0. 0. 0.]
  [0. 0. 0.]]

 [[0. 0. 0.]
  [0. 0. 0.]]

 [[0. 0. 0.]
  [0. 0. 0.]]]

[[[0 0 0]
  [0 0 0]]

 [[0 0 0]
  [0 0 0]]

 [[0 0 0]
  [0 0 0]]]


In [51]:
# All ones matrix
arr=np.ones((3,3),dtype="int16")
print(arr)

[[1 1 1]
 [1 1 1]
 [1 1 1]]


In [53]:
# Initializing using any other number:
arr=np.full((2,2),100)
print(arr)

[[100 100]
 [100 100]]


In [57]:
#Initializing using any other number(full-like):-
arr1=np.array([[[1,2],[2,3]],[[3,4],[5,6]],[[7,8],[8,9]]])
print(arr1)
arr=np.full(arr1.shape,10)
print("\n",arr)
arr=np.full_like(arr1,10)
print("\n",arr)

[[[1 2]
  [2 3]]

 [[3 4]
  [5 6]]

 [[7 8]
  [8 9]]]

 [[[10 10]
  [10 10]]

 [[10 10]
  [10 10]]

 [[10 10]
  [10 10]]]

 [[[10 10]
  [10 10]]

 [[10 10]
  [10 10]]

 [[10 10]
  [10 10]]]


In [67]:
#Initializing array with Random Decimal Numbers
x=np.random.rand(4,3)
print(x)

[[0.55494806 0.09790759 0.98131974]
 [0.74255894 0.06038219 0.10800408]
 [0.05533472 0.90566406 0.68880741]
 [0.57088274 0.11221692 0.49668349]]


In [77]:
#Initializing array with Random Decimal Numbers using another array's shape
x=np.random.random_sample(arr.shape)
print(arr.shape)
print(x)

(3, 2, 2)
[[[0.78960372 0.55348312]
  [0.27387193 0.27411115]]

 [[0.84741623 0.1156743 ]
  [0.6113571  0.45916845]]

 [[0.45143022 0.4436421 ]
  [0.79229192 0.54287361]]]


In [81]:
#Using Random Integers to initialize
x=np.random.randint(7,size=(3,6))
print(x)
x=np.random.randint(3,12,size=(3,6))
print(x)

[[1 6 6 4 5 1]
 [6 6 5 6 1 6]
 [5 3 4 4 3 2]]
[[ 4  7  4  9 10  3]
 [ 3 11  9 10  8 10]
 [11  7  5  9  9  7]]


In [85]:
#Identity Matrix - takes only one parameter cause identity matrices are square matrixes
x=np.identity(3,"int32")
print(x)
x=np.identity(6)
print(x)

[[1 0 0]
 [0 1 0]
 [0 0 1]]
[[1. 0. 0. 0. 0. 0.]
 [0. 1. 0. 0. 0. 0.]
 [0. 0. 1. 0. 0. 0.]
 [0. 0. 0. 1. 0. 0.]
 [0. 0. 0. 0. 1. 0.]
 [0. 0. 0. 0. 0. 1.]]


In [93]:
#Repeating arrays
x=np.repeat([[1,2,3,4]],5,axis=0)
print(x)

[[1 2 3 4]
 [1 2 3 4]
 [1 2 3 4]
 [1 2 3 4]
 [1 2 3 4]]


In [94]:
# Initialize an array like this using whatever we have learned:-
# [[1 1 1 1 1 ]
#  [1 0 0 0 1 ]
#  [1 0 9 0 1 ]
#  [1 0 0 0 1 ]
#  [1 1 1 1 1 ]]

In [103]:
arr=np.ones((5,5),"int32")
arr[1:4,1:4]=0
arr[2,2]=9
print(arr)

[[1 1 1 1 1]
 [1 0 0 0 1]
 [1 0 9 0 1]
 [1 0 0 0 1]
 [1 1 1 1 1]]


In [105]:
arr=np.ones((5,5),"int32")
arr[1:4,1:4]=np.zeros((3,3),"int32")
arr[2,2]=9
print(arr)

[[1 1 1 1 1]
 [1 0 0 0 1]
 [1 0 9 0 1]
 [1 0 0 0 1]
 [1 1 1 1 1]]


### Be careful when copying arrays!!!

In [111]:
a=np.array([1,2,3,4])
b=a.copy()
print(b)
b[0]=25
print(b)
print(a)

[1 2 3 4]
[25  2  3  4]
[1 2 3 4]


# Mathematics

In [115]:
a=np.array([1,2,3,4])
print(a+2) #Element wise addition
print(a-2) #Element wise subtraction
print(a*2) #Element wise multiplication
print(a/2) #Element wise division

[3 4 5 6]
[-1  0  1  2]
[2 4 6 8]
[0.5 1.  1.5 2. ]


In [116]:
b=np.array([1,0,1,0])
print(a+b)

[2 2 4 4]


In [118]:
print(a**2)

[ 1  4  9 16]


In [124]:
#trignometric functions:-
a=np.array([1,2,3,4])
print(np.sin(a))
print(np.cos(a))
print(np.tan(a))

[ 0.84147098  0.90929743  0.14112001 -0.7568025 ]
[ 0.54030231 -0.41614684 -0.9899925  -0.65364362]
[ 1.55740772 -2.18503986 -0.14254654  1.15782128]


In [126]:
# For a lot more (https://docs.scipy.org/doc/numpy/reference/routines.math.html)

### Linear Algebra

In [138]:
a=np.full((2,3),2)
b=np.full((3,2),3)
print(a,"\n    x\n",b)
print("\n",np.matmul(a,b)) #matrix multiplication

[[2 2 2]
 [2 2 2]] 
    x
 [[3 3]
 [3 3]
 [3 3]]

 [[18 18]
 [18 18]]


In [143]:
c=np.identity(3,"int32")
print(c)
print(np.linalg.det(c)) #Finding the determinant

[[1 0 0]
 [0 1 0]
 [0 0 1]]
1.0


In [144]:
## Reference docs (https://docs.scipy.org/doc/numpy/reference/routines.linalg.html)

# Determinant
# Trace
# Singular Vector Decomposition
# Eigenvalues
# Matrix Norm
# Inverse
# Etc...

### Statistics

In [152]:
x=np.array([[1,2,3,4,0],[-45,67,33,12,6]])

In [153]:
print(np.min(x))
print(np.max(x))

-45
67


In [155]:
print(np.min(x,axis=0))
print(np.min(x,axis=1))
print(np.max(x,axis=0))
print(np.max(x,axis=1))

[-45   2   3   4   0]
[  0 -45]
[ 1 67 33 12  6]
[ 4 67]


In [158]:
print(np.sum(x,axis=None))
print(np.sum(x,axis=0))
print(np.sum(x,axis=1))

83
[-44  69  36  16   6]
[10 73]


### Reorganizing arrays:-

In [162]:
x=np.array([[1,2,3,4],[5,6,7,8]])
print(x,x.shape)

[[1 2 3 4]
 [5 6 7 8]] (2, 4)


In [164]:
print(x.reshape((8,1)))
print(x.reshape((1,8)))
print(x.reshape((4,2)))
print(x.reshape((2,2,2)))

[[1]
 [2]
 [3]
 [4]
 [5]
 [6]
 [7]
 [8]]
[[1 2 3 4 5 6 7 8]]
[[1 2]
 [3 4]
 [5 6]
 [7 8]]
[[[1 2]
  [3 4]]

 [[5 6]
  [7 8]]]


In [169]:
## Vertically & Horizontally Stacking Vectors

In [170]:
a=np.array([1,2,3,4])
b=np.array([5,6,7,8])
x=np.vstack((a,b,a,b))
print(x)
x=np.hstack((a,b,a,b))
print(x)

[[1 2 3 4]
 [5 6 7 8]
 [1 2 3 4]
 [5 6 7 8]]
[1 2 3 4 5 6 7 8 1 2 3 4 5 6 7 8]


In [173]:
a=np.zeros((2,5))
b=np.ones((2,2))
print(np.hstack((a,b)))

[[0. 0. 0. 0. 0. 1. 1.]
 [0. 0. 0. 0. 0. 1. 1.]]


In [175]:
a=np.zeros((2,5))
b=np.ones((3,5))
print(np.vstack((a,b)))

[[0. 0. 0. 0. 0.]
 [0. 0. 0. 0. 0.]
 [1. 1. 1. 1. 1.]
 [1. 1. 1. 1. 1.]
 [1. 1. 1. 1. 1.]]


### Miscellaneous

#### Load Data from File

In [184]:
x=np.genfromtxt("data.txt",delimiter=",",dtype="int32")
print(x)
print()
print(x.astype("float64"))

[[  1  13  21  11 196  75   4   3  34   6   7   8   0   1   2   3   4   5]
 [  3  42  12  33 766  75   4  55   6   4   3   4   5   6   7   0  11  12]
 [  1  22  33  11 999  11   2   1  78   0   1   2   9   8   7   1  76  88]]

[[  1.  13.  21.  11. 196.  75.   4.   3.  34.   6.   7.   8.   0.   1.
    2.   3.   4.   5.]
 [  3.  42.  12.  33. 766.  75.   4.  55.   6.   4.   3.   4.   5.   6.
    7.   0.  11.  12.]
 [  1.  22.  33.  11. 999.  11.   2.   1.  78.   0.   1.   2.   9.   8.
    7.   1.  76.  88.]]


#### Advanced Indexing

In [188]:
print(x>50)

[[False False False False  True  True False False False False False False
  False False False False False False]
 [False False False False  True  True False  True False False False False
  False False False False False False]
 [False False False False  True False False False  True False False False
  False False False False  True  True]]


In [189]:
print(x[x>50])

[196  75 766  75  55 999  78  76  88]


In [191]:
### You can index with a list in Numpy
arr=np.array([1,2,3,4,5,6,7,8,9,10])
print(arr[[1,5,8]])

[2 6 9]


In [197]:
print(x)
print(np.any(x>50,axis=0))
print(np.any(x>50,axis=1))

[[  1  13  21  11 196  75   4   3  34   6   7   8   0   1   2   3   4   5]
 [  3  42  12  33 766  75   4  55   6   4   3   4   5   6   7   0  11  12]
 [  1  22  33  11 999  11   2   1  78   0   1   2   9   8   7   1  76  88]]
[False False False False  True  True False  True  True False False False
 False False False False  True  True]
[ True  True  True]


In [200]:
print(np.all(x>50,axis=0))
print(np.all(x>50,axis=1))

[False False False False  True False False False False False False False
 False False False False False False]
[False False False]


In [201]:
((x>50)&(x<100))

array([[False, False, False, False, False,  True, False, False, False,
        False, False, False, False, False, False, False, False, False],
       [False, False, False, False, False,  True, False,  True, False,
        False, False, False, False, False, False, False, False, False],
       [False, False, False, False, False, False, False, False,  True,
        False, False, False, False, False, False, False,  True,  True]])

In [202]:
(~((x>50)&(x<100)))

array([[ True,  True,  True,  True,  True, False,  True,  True,  True,
         True,  True,  True,  True,  True,  True,  True,  True,  True],
       [ True,  True,  True,  True,  True, False,  True, False,  True,
         True,  True,  True,  True,  True,  True,  True,  True,  True],
       [ True,  True,  True,  True,  True,  True,  True,  True, False,
         True,  True,  True,  True,  True,  True,  True, False, False]])

In [233]:
#Some short quiz:-
matrix=np.array([list(range(1,31))]).reshape((6,5))
print(matrix)
print()
print(matrix[2:4,0:2])
print()
print(matrix[0:4,1:5].diagonal())
print()
print(matrix[[0,1,2,3],[1,2,3,4]])
print()
print(matrix[[0,0,4,4,5,5],[3,4,3,4,3,4]].reshape((3,2)))
print()
print(matrix[[0,4,5],3:5])

[[ 1  2  3  4  5]
 [ 6  7  8  9 10]
 [11 12 13 14 15]
 [16 17 18 19 20]
 [21 22 23 24 25]
 [26 27 28 29 30]]

[[11 12]
 [16 17]]

[ 2  8 14 20]

[ 2  8 14 20]

[[ 4  5]
 [24 25]
 [29 30]]

[[ 4  5]
 [24 25]
 [29 30]]
